# Generated by Django 5.1.1 on 2024-09-22 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_sensor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='device',
            new_name='device_id',
        ),
    ]
