# Generated by Django 5.1.1 on 2024-09-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_sensor', '0002_rename_device_sensordata_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='datetime',
            field=models.CharField(default='2024-01-01 00:00:00', max_length=128),
        ),
    ]
